name: Testes + Allure Report

on:
  push:
    branches: [ "main" ]   # ajusta se tua branch principal tiver outro nome
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm ci   # mais rápido e recomendado no CI

      - name: rodar os testes de Integração
        run: npx jest

      - name: Instalar Chromium do Playwright
        run: npx playwright install --with-deps chromium

      - name: Rodar testes com Allure
        run: |
          npx playwright test --reporter=line,allure-playwright
          # Gera o relatório bruto do Allure
          npx allure generate allure-results --clean -o allure-report

      - name: Preparar histórico
        run: |
          mkdir -p allure-history      # Cria pasta p/ histórico
          rm -rf allure-history/* || true    # Limpa conteúdos antigos
          cp -r allure-report/* allure-history/  # Copia novo relatório
          touch allure-history/.nojekyll   # evita bug do GitHub Pages com underline/_

      - name: Publicar no GitHub Pages
        if: always()   # publica mesmo se os testes falharem
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-history
          keep_files: true   # mantém histórico do Allure
